spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/demo_db
    username: demo_user
    password: demo_pass
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    #    show-sql: true
    open-in-view: false
    properties:
      #      hibernate.generate_statistics: true
      #      hibernate.format_sql: true
      hibernate.ddl-auto: none
      hibernate.connection.provider_disables_autocommit: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.jdbc.time_zone: UTC
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      #      javax.persistence.schema-generation.create-source: metadata
      #      javax.persistence.schema-generation.scripts.action: create
      #      javax.persistence.schema-generation.scripts.create-target: create.sql
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  mvc:
    servlet:
      load-on-startup: 1

logging:
  level:
    net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener: DEBUG

springdoc:
  cache:
    disabled: true
  swagger-ui:
    showCommonExtensions: true
    showExtensions: true

