version: "3.3"
services:

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./_infrastructure/postgres/datadir:/var/lib/postgresql/data
      - ./_infrastructure/postgres/init/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

